export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SELECT_EXHIBITION = "SELECT_EXHIBITION"
export const SELECT_BOOTH = "SELECT_BOOTH"
export const SWITCH_TO_EDIT = "SWITCH_TO_EDIT"
export const SWITCH_SIDE_MENU = "SWITCH_SIDE_MENU"
